#include <nuttx/config.h>
#include <systemlib/param/param.h>
PARAM_DEFINE_FLOAT(MCC_RPM_MIN, 1000.0f);
PARAM_DEFINE_FLOAT(MCC_RPM_START, 1200.0f);
PARAM_DEFINE_FLOAT(MCC_RPM_MAX, 8000.0f);
PARAM_DEFINE_FLOAT(MCC_CT, 1.0e-8f);
PARAM_DEFINE_FLOAT(MCC_MOMENT_SCALE, 0.025f);
PARAM_DEFINE_FLOAT(MCC_ARM_LENGTH, 0.17933f);
PARAM_DEFINE_FLOAT(MCC_TOTAL_MASS, 1.00f);
PARAM_DEFINE_FLOAT(MCC_MOTOR_SPREAD, 0.7854f);
PARAM_DEFINE_FLOAT(MCC_INERTIA_XX, 0.0f);
PARAM_DEFINE_FLOAT(MCC_INERTIA_XY, 0.0f);
PARAM_DEFINE_FLOAT(MCC_INERTIA_XZ, 0.0f);
PARAM_DEFINE_FLOAT(MCC_INERTIA_YY, 0.0f);
PARAM_DEFINE_FLOAT(MCC_INERTIA_YZ, 0.0f);
PARAM_DEFINE_FLOAT(MCC_INERTIA_ZZ, 0.0f);
PARAM_DEFINE_FLOAT(MCC_GRAVITY, 9.80f);
PARAM_DEFINE_FLOAT(MCC_MOT_START_DT, 0.5f);
PARAM_DEFINE_FLOAT(MCC_MOTOR_CONST, 20.0f);

/* EPC Params */
PARAM_DEFINE_FLOAT(DT_, 0.01f);
PARAM_DEFINE_INT32(HORIZON_LENGTH, 2);
PARAM_DEFINE_INT32(NUM_STATES, 6);
PARAM_DEFINE_INT32(NUM_INPUTS, 3);


PARAM_DEFINE_FLOAT(MCC_CMD_TTL, 0.3f);
PARAM_DEFINE_INT32(MCC_PWM_MAP1, 1);
PARAM_DEFINE_INT32(MCC_PWM_MAP2, 2);
PARAM_DEFINE_INT32(MCC_PWM_MAP3, 3);
PARAM_DEFINE_INT32(MCC_PWM_MAP4, 4);
PARAM_DEFINE_INT32(MCC_PWM_RATE, 500);

PARAM_DEFINE_FLOAT(MCC_RPM_PER_PWM, 0.0f);
PARAM_DEFINE_FLOAT(MCC_RPM_PER_VOLT, 0.0f);
PARAM_DEFINE_FLOAT(MCC_RPM_V_ZERO, 0.0f);

PARAM_DEFINE_INT32(MCC_ENABLE_L1C, 0);
PARAM_DEFINE_INT32(L1C_ACTIVE, 0);
PARAM_DEFINE_FLOAT(L1C_BW_X, 0.0f);
PARAM_DEFINE_FLOAT(L1C_BW_Y, 0.0f);
PARAM_DEFINE_FLOAT(L1C_BW_Z, 0.0f);
PARAM_DEFINE_FLOAT(L1C_OBS_GAIN_X, 400.0f);
PARAM_DEFINE_FLOAT(L1C_OBS_GAIN_Y, 400.0f);
PARAM_DEFINE_FLOAT(L1C_OBS_GAIN_Z, 400.0f);
PARAM_DEFINE_FLOAT(L1C_ADAPT_GAIN_X, 10.0f);
PARAM_DEFINE_FLOAT(L1C_ADAPT_GAIN_Y, 10.0f);
PARAM_DEFINE_FLOAT(L1C_ADAPT_GAIN_Z, 10.0f);
PARAM_DEFINE_FLOAT(L1C_INIT_DIST_X, 0.0f);
PARAM_DEFINE_FLOAT(L1C_INIT_DIST_Y, 0.0f);
PARAM_DEFINE_FLOAT(L1C_INIT_DIST_Z, 0.0f);
PARAM_DEFINE_FLOAT(L1C_ENGAGE_LEVEL, 0.3f);
PARAM_DEFINE_INT32(L1C_ENABLE_DEBUG, 0);

PARAM_DEFINE_INT32(MCC_ENABLE_L1P, 0);
PARAM_DEFINE_INT32(L1P_ACTIVE, 0);
PARAM_DEFINE_FLOAT(L1P_BW_X, 5.0f);
PARAM_DEFINE_FLOAT(L1P_BW_Y, 5.0f);
PARAM_DEFINE_FLOAT(L1P_BW_Z, 5.0f);
PARAM_DEFINE_FLOAT(L1P_OBS_GAIN_X, 100.0f);
PARAM_DEFINE_FLOAT(L1P_OBS_GAIN_Y, 100.0f);
PARAM_DEFINE_FLOAT(L1P_OBS_GAIN_Z, 100.0f);
PARAM_DEFINE_FLOAT(L1P_ADAPT_GAIN_X, 3000.0f);
PARAM_DEFINE_FLOAT(L1P_ADAPT_GAIN_Y, 3000.0f);
PARAM_DEFINE_FLOAT(L1P_ADAPT_GAIN_Z, 1000.0f);
PARAM_DEFINE_FLOAT(L1P_INIT_DIST_X, 0.0f);
PARAM_DEFINE_FLOAT(L1P_INIT_DIST_Y, 0.0f);
PARAM_DEFINE_FLOAT(L1P_INIT_DIST_Z, 0.0f);
PARAM_DEFINE_FLOAT(L1P_ENGAGE_LEVEL, 0.37f);
PARAM_DEFINE_INT32(L1P_ENABLE_DEBUG, 0);
